### ISSUE TITLE
indexingThreshold

### ISSUE THREAD

**Issue by lukaszknasiecki** [hkulekci/qdrant-php#48]
indexingThreshold value may be set to 0 (as per QDrant docs), but then it's ignored and skipped in the request

OptimizersConfig.php
simple fix:

if ($this->indexingThreshold || **$this->indexingThreshold===0**) {
            $data['indexing_threshold'] = $this->indexingThreshold;
        }

**Comment by hkulekci** [comment]
Fix merged!. Feel free to reach out after your test.
